# Generated by Django 6.0.7 on 2026-08-17 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.FileField(blank=True, upload_to='workspace_logos/')),
                ('profile_image', models.FileField(blank=True, upload_to='workspace_profile_images/')),
                ('description', models.TextField(blank=True)),
                ('brand_color', models.CharField(blank=True, max_length=7)),
                ('currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=64)),
                ('whatsapp_number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
