# Generated by Django 6.0.7 on 2026-08-19 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INSTAPAY', 'InstaPay'), ('VODAFONE_CASH', 'Vodafone Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CUSTOM', 'Custom')], max_length=13)),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('account_details', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='payment_method_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
